name: Azure Static Web Apps CI/CD
on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.19'
      - name: Create staticwebapp.config.json
        run: |
          echo '{
            "navigationFallback": {
              "rewrite": "/index.html",
              "exclude": ["/images/*.{png,jpg,gif}", "/css/*", "/assets/*"]
            },
            "routes": [
              {
                "route": "/*",
                "serve": "/index.html",
                "statusCode": 200
              }
            ],
            "platformErrorOverrides": [
              {
                "errorType": "NotFound",
                "serve": "/index.html",
                "statusCode": 200
              }
            ]
          }' > ./Frontend/staticwebapp.config.json
      - name: Install dependencies
        run: npm install
        working-directory: ./Frontend
      - name: Build the Angular app
        run: npm run build -- --output-path=dist/frontend
        working-directory: ./Frontend
      - name: List output directory
        run: ls -R ./Frontend/dist/frontend
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_GROUND_083F7CE10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_deploy_on_missing_secrets: true
          app_location: "./Frontend"
          api_location: "./AIFunctionApp"
          output_location: "dist/frontend"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_GROUND_083F7CE10 }}
          action: "close"
